export const ADD_USERS_FAVORITES = 'ADD_USERS_FAVORITES';
export const INFO_FAVORITES_SUCCESS = 'INFO_FAVORITES_SUCCESS';
export const GET_FAVORITES = 'GET_FAVORITES'
export const DELETE_FAVORITES = 'DELETE_FAVORITES'
export const FAV = 'FAV'